### ISSUE TITLE
Unable to find MOOSE executable when running through WSL VS Code Instance

### ISSUE THREAD

**Issue by ARFalkowski** [idaholab/moose-language-support#11]
I'm trying to run this extension in VS Code on a Windows machine accessing MOOSE directories through the WSL. When I open VS Code with `~/projects/AnyMooseApp$ code .` and try to open auto-complete, I get the following error: `No MOOSE application executable found.`. If I could get some help resolving this issue, that would be great!

**Comment by dschwen** [comment]
Hm, have you tried using the VSCode remote editing capability for WSL? Are you actually using a VSCode installed within WSL? What is your file path and have you sucessfully built a MOOSE executable (if so what's its path)?

**Comment by ARFalkowski** [comment]
Seems to be that I wasn't running[ remote development extension pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack), once installed extension works. Thank you.
