### ISSUE TITLE
vscode 1.82 cannot connect to the moose language server in WSL

### ISSUE THREAD

**Issue by Ramzy1990** [idaholab/moose-language-support#15]
I encountered the following error on [vscode 1.82](https://code.visualstudio.com/updates/v1_82):
```
RuntimeError: abort(TypeError: Failed to parse URL from /home/ramzy/.vscode-server/extensions/danielschwen.moose-language-support-0.6.1/server/node_modules/web-tree-sitter/tree-sitter.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.we (/home/ramzy/.vscode-server/extensions/danielschwen.moose-language-support-0.6.1/server/node_modules/web-tree-sitter/tree-sitter.js:1:11339)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v18.15.0
[Error - 3:47:37 PM] Connection to server got closed. Server will not be restarted.
```
This error appears while using either the 0.6.0 or the updated 0.6.1 (and even the 0.5.1) on WSL through a vscode server. Tried it on different WSL Linux distributions (Ubuntu-22.04 and Ubuntu-23.10 (through [Ubuntu-Preview](https://apps.microsoft.com/store/detail/ubuntu-preview/9P7BDVKVNXZ6))).

Downgrading to [vscode 1.81](https://code.visualstudio.com/updates/v1_81) solves this problem. It seems to be related with upgrading Node.js to version 18 from 16 in the latest vscode 1.82 as explained [here](https://code.visualstudio.com/updates/v1_82#_update-highlights-for-nodejs).

**Comment by dschwen** [comment]
Thanks for reporting this. I'll have a look.

**Comment by dschwen** [comment]
Ok, check `v0.6.2` it works for me in VSCode 1.82

**Comment by Ramzy1990** [comment]
Thank you for the prompt hotfix! The main issue has been solved, but now the "Malformed Input." warning appears whenever the file is saved, even if it confirms to the hit file check (supposedly). I tried it with both old and new inputs. The autocomplete works flawlessly though as seen in the gif:

![Malformed Input](https://github.com/idaholab/moose-language-support/assets/30245545/7cab3363-98d6-4957-a357-70191f8da730)

Here is the output of the extension if it helps:

![image](https://github.com/idaholab/moose-language-support/assets/30245545/4fa0f33d-a5fa-4d34-b9a5-0e15ff97dae6)

I am not sure, but could it be that in [the commits](https://github.com/idaholab/moose-language-support/commits/main) you reverted the [following WASP's commit two times](https://github.com/idaholab/moose-language-support/commit/f1f0b8aaed58a2f5db0a8b03feee23184e7b4bb7) that it returned to its [old commit](https://github.com/idaholab/moose-language-support/commit/7f7080df4a7ab12cb002bbd044b2c534162940de) removed in newer versions? I noticed my WASP directory is empty inside the moose framework.
