### ISSUE TITLE
Feature Request: Specify Comment Character

### ISSUE THREAD

**Issue by maxnezdyur** [idaholab/moose-language-support#5]
VS code doesn't know the comment character for the file. This keeps me from highlighting a block of code and commenting it all out. It is possible for me to fix this on my settings and add the comment character for .i files, but I think this would be useful in general for this extension.

**Comment by maxnezdyur** [comment]
I haven't ever written an extension, but I may try to implement this later. The resource I found for this is here. https://code.visualstudio.com/api/language-extensions/language-configuration-guide  This would also allow one to setup auto-closing brackets.

**Comment by dschwen** [comment]
Oh yeah, this would be nice. We're currently also missing Auto indent, which the atom language extension had as part of the syntax highlight file. That was lost in conversion and apparently is configured in a different file in vscode.

**Comment by maxnezdyur** [comment]
I believe auto indent is also configured in the link I sent.
Here is a snippet 
  "indentationRules": {
    "increaseIndentPattern": "^((?!\\/\\/).)*(\\{[^}\"'`]*|\\([^)\"'`]*|\\[[^\\]\"'`]*)$",
    "decreaseIndentPattern": "^((?!.*?\\/\\*).*\\*/)?\\s*[\\}\\]].*$"
  }
It seems easier than I thought it would be to implement, I might have to pull your repo later and add other things that come to my mind.
